apiVersion: v1
kind: Secret
metadata:
  name: apache-userdata
type: Opaque
stringData:
  value: |
    #cloud-config
    package_update: true
    packages:
      - httpd
      - firewalld

    write_files:
      - path: /var/www/html/index.html
        permissions: '0644'
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Hello from OpenStack!</title>
              <style>
                  body { font-family: Arial; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; }
                  .container { text-align: center; padding: 40px; background: rgba(255,255,255,0.1); border-radius: 10px; }
                  h1 { font-size: 3em; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>Hello World!</h1>
                  <p>Deployed via GitOps with ArgoCD + ORC</p>
              </div>
          </body>
          </html>

    runcmd:
      - systemctl enable firewalld && systemctl start firewalld
      - firewall-cmd --permanent --add-service=http && firewall-cmd --reload
      - systemctl enable httpd && systemctl start httpd
